--7.Display all department name and  street address
SELECT DEPARTMENT_NAME,STREET_ADDRESS FROM DEPARTMENTS D
    FULL JOIN LOCATIONS L ON D.LOCATION_ID = L.LOCATION_ID;

--8.Display first_name,last_name and department_name,city for all employees
SELECT FIRST_NAME,LAST_NAME,DEPARTMENT_NAME ,CITY FROM EMPLOYEES
    JOIN DEPARTMENTS ON EMPLOYEES.DEPARTMENT_ID = DEPARTMENTS.DEPARTMENT_ID
    JOIN LOCATIONS l ON DEPARTMENTS.LOCATION_ID = l.LOCATION_ID;

--9.Display first_name,last_name and department_name,city,country_name for all employees
select FIRST_NAME,LAST_NAME,DEPARTMENT_NAME ,CITY,COUNTRY_NAME FROM EMPLOYEES
     JOIN DEPARTMENTS on EMPLOYEES.DEPARTMENT_ID = DEPARTMENTS.DEPARTMENT_ID
     JOIN LOCATIONS l on DEPARTMENTS.LOCATION_ID = l.LOCATION_ID
     JOIN COUNTRIES C2 on l.COUNTRY_ID = C2.COUNTRY_ID;
--10.Display first_name,last_name and department_name,city who is living in United Kingdom
select FIRST_NAME,LAST_NAME,DEPARTMENT_NAME ,CITY FROM EMPLOYEES
     JOIN DEPARTMENTS ON EMPLOYEES.DEPARTMENT_ID = DEPARTMENTS.DEPARTMENT_ID
     JOIN LOCATIONS l ON DEPARTMENTS.LOCATION_ID = l.LOCATION_ID AND CITY='United Kingdom';
--11.Display how many employee we have for each country name
SELECT COUNTRY_NAME , COUNT(*) AS COUNT_EMPLOYEE FROM EMPLOYEES
    JOIN DEPARTMENTS ON EMPLOYEES.DEPARTMENT_ID = DEPARTMENTS.DEPARTMENT_ID
    JOIN LOCATIONS l ON DEPARTMENTS.LOCATION_ID = l.LOCATION_ID
    JOIN COUNTRIES C2 ON l.COUNTRY_ID = C2.COUNTRY_ID GROUP BY COUNTRY_NAME ORDER BY COUNTRY_NAME;
