
   select * from employees;

   SELECT distinct (JOB_ID) FROM EMPLOYEES
   WHERE JOB_ID=8;


   select JOB_ID, AVG(SALARY)
   from EMPLOYEES where JOB_ID='IT_PROG' GROUP BY JOB_ID;

   select MIN(SALARY),JOB_ID
   from EMPLOYEES where JOB_ID='IT_PROG' GROUP BY JOB_ID;

   select JOB_ID, MIN(SALARY),MAX(SALARY),SUM(SALARY),COUNT(*)
   from EMPLOYEES  GROUP BY JOB_ID;

   select SUM(SALARY),DEPARTMENT_ID
   from EMPLOYEES  GROUP BY DEPARTMENT_ID;

   SELECT MAX(SALARY),DEPARTMENT_ID FROM EMPLOYEES GROUP BY DEPARTMENT_ID;

   SELECT SALARY,DEPARTMENT_ID FROM EMPLOYEES GROUP BY DEPARTMENT_ID, SALARY HAVING AVG(SALARY)>6000;







